FROM php:8.3-apache

# Configure PHP
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN apt-get update && apt-get install --no-install-recommends -y \
        libmagickwand-dev \
    && pecl install imagick \
    && docker-php-ext-enable imagick


# Configure Apache
RUN a2enmod rewrite

# Update document root to public folder
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf


RUN groupmod -g 1000 www-data && usermod -u 1000 www-data
USER www-data
