<?php

/**
 * German translations for the Advent Calendar application.
 * DO NOT EDIT THIS FILE - add custom translations to de.local.php
 */

return [
    'Advent Calendar' => 'Adventskalender',
    'Select Language' => 'Sprache auswählen',
    'Home' => 'Startseite',
    'Day' => 'Tag',
    'Open' => 'Öffnen',
    'Login' => 'Anmelden',
    'Password' => 'Passwort',
    'Close' => 'Schließen',
    'Server error' => 'Serverfehler',
    'Invalid password' => 'Falsches Passwort',
    'Logout' => 'Abmelden',
    'Close all doors and log out' => 'Alle Türen schließen und abmelden',
    'Download' => 'Herunterladen',
    'Door will open on' => 'Tür öffnet sich am',
    'day' => 'Tag',
    'days' => 'Tage',
    'Y-m-d' => 'd.m.Y',
];
